version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/core"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/relay"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/desktop"
    schedule:
      interval: "weekly"
